# Generated by Django 4.1.4 on 2022-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_api", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="user",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=123, upload_to="product/", verbose_name="Фотография"
            ),
            preserve_default=False,
        ),
    ]
